"""Write the deck out as files, for review and for the day itself.

    flask --app acb_large_print_web.app:create_app workshop-deck
    flask --app acb_large_print_web.app:create_app workshop-deck --code ahg-2026

The deck is served live at ``/workshop/session/<code>/deck`` and that is what
a facilitator should project. This command exists for the two cases a served
page cannot cover: reviewing the whole deck as files in one folder, and
having every format already on a laptop before walking into a room whose
network you do not control.

Everything written is generated. Edit ``workshop_deck.py`` and run this
again; do not edit the output, because the next run will overwrite it.
"""

from __future__ import annotations

from pathlib import Path

import click
from flask import Flask

from . import workshop_deck as deck
from .routes.workshop import ACTIVITY_META, ACTIVITY_ORDER

DEFAULT_OUT = Path("docs/ahg-2026")
BASENAME = "slides"

GENERATED_NOTE = (
    "<!-- Generated by: flask --app acb_large_print_web.app:create_app "
    "workshop-deck. Edit web/src/acb_large_print_web/workshop_deck.py, not "
    "this file. -->\n"
)
GENERATED_NOTE_MD = (
    "<!-- Generated from web/src/acb_large_print_web/workshop_deck.py by "
    "`flask --app acb_large_print_web.app:create_app workshop-deck`. "
    "Do not edit this file; edit the module and regenerate. -->\n\n"
)


def register_cli(app: Flask) -> None:
    @app.cli.command("workshop-deck")
    @click.option("--code", default="", help="Session code to write into the deck.")
    @click.option(
        "--host",
        default="letitglow.app",
        show_default=True,
        help="Host used for the join address on the deck.",
    )
    @click.option(
        "--out",
        default=str(DEFAULT_OUT),
        show_default=True,
        type=click.Path(file_okay=False),
        help="Directory to write into.",
    )
    def workshop_deck_command(code: str, host: str, out: str) -> None:
        """Write the deck as HTML, Markdown, Word and PowerPoint."""
        from flask import render_template

        code_label = (code or "").strip() or "your-code"
        ctx = deck.DeckContext(
            code_label=code_label,
            join_display=f"{host}/w/{code_label}",
            activity_times=tuple(ACTIVITY_META[key]["time"] for key in ACTIVITY_ORDER),
        )

        out_dir = Path(out)
        out_dir.mkdir(parents=True, exist_ok=True)

        html = render_template(
            "workshop/deck.html",
            deck_title=f"{deck.DECK_TITLE} - workshop deck",
            slides=deck.build_slides(ctx),
            download_urls={
                "html": f"{BASENAME}.html",
                "md": f"{BASENAME}.md",
                "docx": f"{BASENAME}.docx",
                "pptx": f"{BASENAME}.pptx",
            },
            csp_nonce="",
        )

        # The served page carries a per-request CSP nonce. A file on a laptop
        # has no CSP to satisfy, so drop the empty attribute rather than ship
        # markup that looks like a mistake.
        html = html.replace(' nonce=""', "")

        written: list[tuple[Path, int]] = []

        html_path = out_dir / f"{BASENAME}.html"
        html_path.write_text(GENERATED_NOTE + html, encoding="utf-8")
        written.append((html_path, len(html)))

        md_path = out_dir / f"{BASENAME}.md"
        md_path.write_text(GENERATED_NOTE_MD + deck.build_deck_markdown(ctx), encoding="utf-8")
        written.append((md_path, md_path.stat().st_size))

        docx_path = out_dir / f"{BASENAME}.docx"
        docx_path.write_bytes(deck.build_deck_docx_bytes(ctx))
        written.append((docx_path, docx_path.stat().st_size))

        pptx_path = out_dir / f"{BASENAME}.pptx"
        pptx_path.write_bytes(deck.build_deck_pptx_bytes(ctx))
        written.append((pptx_path, pptx_path.stat().st_size))

        slide_count = len(deck.build_slides(ctx))
        click.echo(f"{slide_count} slides, join address {ctx.join_display}")
        for path, size in written:
            click.echo(f"  {path}  ({size:,} bytes)")
        if code_label == "your-code":
            click.echo(
                "\nNo --code given, so the deck says 'your-code'. Re-run with "
                "--code <session> once the conference code is set."
            )
